# Generated by Django 3.0.4 on 2020-03-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('relator', models.CharField(max_length=128, verbose_name='Relator')),
                ('orientador', models.CharField(max_length=128, verbose_name='Orientador')),
                ('programa', models.CharField(max_length=20, verbose_name='Programa')),
                ('relatorio', models.CharField(max_length=20, verbose_name='Relatório')),
                ('encaminhamento', models.CharField(max_length=20, verbose_name='Encaminhamento')),
            ],
        ),
    ]
