# Generated by Django 3.0.4 on 2020-04-01 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_relatorios_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorios',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='envio'),
            preserve_default=False,
        ),
    ]
