# Generated by Django 3.0.4 on 2020-04-07 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sispos.relatorios.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relatorios', '0005_relatorios_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorios',
            name='relator',
            field=models.ForeignKey(limit_choices_to=sispos.relatorios.models.limit_to_relator, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relator', to=settings.AUTH_USER_MODEL),
        ),
    ]
