# Generated by Django 3.0.4 on 2020-04-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0006_auto_20200407_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorios',
            name='semestre',
            field=models.CharField(choices=[('rds1', 'Primeiro semestre'), ('rds2', 'Segundo semestre'), ('rds3', 'Terceriro semestre'), ('rds4', 'Quarto semestre'), ('rds5', 'Quinto semestre'), ('rds6', 'Sexto semestre'), ('rds7', 'Sétimo semestre')], default='rds1', max_length=20, verbose_name='semestre'),
            preserve_default=False,
        ),
    ]
