# Generated by Django 3.0.4 on 2020-04-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0007_relatorios_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorios',
            name='state',
            field=models.CharField(choices=[('waiting_relator', 'Aguardando parecer'), ('waiting_parecer_relator', 'Avaliado')], default='Aguardando parecer', max_length=128, verbose_name='state'),
        ),
    ]
