# Generated by Django 3.0.4 on 2020-04-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0009_auto_20200423_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorios',
            name='state',
            field=models.CharField(choices=[('waiting_relator', 'Aguardando'), ('relator_asigned', 'Encaminhado'), ('waiting_parecer_relator', 'Aguardando'), ('parecer_relator_submited', 'Enviado')], default='waiting_relator', max_length=128, verbose_name='state'),
        ),
    ]
