# Generated by Django 3.0.4 on 2020-04-28 19:58

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0010_auto_20200423_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorios',
            name='encaminhamento',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='encaminhamentos/%Y/%m/%d/', verbose_name='Encaminhamento'),
        ),
    ]
