# Generated by Django 3.0.4 on 2020-04-28 20:06

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0011_auto_20200428_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorios',
            name='relatorio',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='relatorios/%Y/%m/%d/', verbose_name='Relatório'),
        ),
    ]
