# Generated by Django 3.0.4 on 2020-04-10 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relatorios', '0006_auto_20200407_2105'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rds1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desempenho', models.CharField(max_length=2048, verbose_name='desempenho')),
                ('revisao', models.CharField(max_length=2048, verbose_name='revisao')),
                ('definicao', models.CharField(max_length=2048, verbose_name='definicao')),
                ('plano', models.CharField(max_length=2048, verbose_name='planos')),
                ('resultados', models.CharField(max_length=2048, verbose_name='resultados')),
                ('atividades', models.CharField(max_length=2048, verbose_name='atividades')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.Relatorios')),
            ],
        ),
    ]
