# Generated by Django 3.0.4 on 2020-04-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parecer', '0002_auto_20200413_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='rds1',
            name='status',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='aprovado', max_length=12, verbose_name='status'),
            preserve_default=False,
        ),
    ]
