# Generated by Django 3.0.4 on 2020-04-14 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0006_auto_20200407_2105'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parecer', '0003_rds1_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rds2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desempenho', models.CharField(max_length=2048, verbose_name='desempenho')),
                ('metodologia', models.CharField(max_length=2048, verbose_name='metodologia')),
                ('resultados', models.CharField(max_length=2048, verbose_name='resultados')),
                ('esboco', models.CharField(max_length=2048, verbose_name='esboco')),
                ('atividades', models.CharField(max_length=2048, verbose_name='atividades')),
                ('status', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], max_length=2048, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('relator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.Relatorios')),
            ],
        ),
    ]
