# Generated by Django 3.0.4 on 2020-04-15 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0007_relatorios_semestre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parecer', '0004_rds2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rds3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultados', models.CharField(max_length=2048, verbose_name='reesultados')),
                ('artigo', models.CharField(max_length=2048, verbose_name='artigo')),
                ('atividades', models.CharField(max_length=2048, verbose_name='atividades')),
                ('status', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], max_length=20, verbose_name='status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.Relatorios')),
            ],
        ),
    ]
