# Generated by Django 3.0.4 on 2020-04-15 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relatorios', '0007_relatorios_semestre'),
        ('parecer', '0005_rds3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rds4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspectiva', models.CharField(max_length=2048, verbose_name='perspectivas')),
                ('status', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], max_length=2048, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('relator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.Relatorios')),
            ],
        ),
    ]
